# Generated by Django 5.0 on 2023-12-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_userpurchase_car_alter_userpurchase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
