# Generated by Django 5.0 on 2023-12-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_alter_userpurchase_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='car_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
