# Generated by Django 5.0 on 2023-12-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0004_alter_userpurchase_car_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='car_quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
