# Generated by Django 5.0 on 2023-12-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_alter_userpurchase_car_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurchase',
            name='car_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userpurchase',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
